"""
Basic types and structural models for the CAMARA Application Endpoint Registration API.

This module contains the fundamental data types used across the API including
edge cloud zone definitions, domain names, IP addresses, and other basic types.
"""

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# Regex patterns for validation
FQDN_PATTERN = (
    r"^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?"  # First label
    r"(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)+$"  # Additional labels (at least one required)
)

# IPv6 address pattern - covers all valid IPv6 formats including:
# - Full notation (8 groups of 4 hex digits)
# - Compressed notation with ::
# - IPv4-mapped IPv6 addresses
# - Link-local addresses with zone identifiers
IPV6_PATTERN = (
    r"^("
    r"([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|"  # Full form
    r"([0-9a-fA-F]{1,4}:){1,7}:|"  # Compressed ending with ::
    r"([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|"  # 1 compressed group
    r"([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|"  # 2 compressed groups
    r"([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|"  # 3 compressed groups
    r"([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|"  # 4 compressed groups
    r"([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|"  # 5 compressed groups
    r"[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|"  # 6 compressed groups
    r":((:[0-9a-fA-F]{1,4}){1,7}|:)|"  # Leading :: compression
    r"fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|"  # Link-local with zone
    r"::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}"
    r"(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|"  # IPv4-mapped
    r"([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}"
    r"(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])"  # IPv4-compatible
    r")$"
)

# DNS label pattern (alphanumeric with hyphens, max 63 chars, no leading/trailing hyphen)
DNS_LABEL_PATTERN = r"^[A-Za-z0-9]([A-Za-z0-9-]{0,53}[A-Za-z0-9])?$"


# Basic type definitions
class EdgeCloudZoneStatus(str, Enum):
    """Status of an Edge Cloud Zone"""

    ACTIVE = "active"
    INACTIVE = "inactive"
    UNKNOWN = "unknown"


class DomainName(BaseModel):
    """
    A fully qualified domain name (FQDN) as per RFC 1035, section 2.3.1.
    """

    value: str = Field(
        ...,
        pattern=FQDN_PATTERN,
        min_length=4,
        max_length=253,
        examples=["api.example.com", "server.zone1.provider.com"],
    )


class SingleIpv6Addr(BaseModel):
    """
    A single IPv6 address as defined in RFC 4291.
    """

    value: str = Field(
        ...,
        pattern=IPV6_PATTERN,
        examples=["2001:db8:85a3:8d3:1319:8a2e:370:7344"],
    )


class EdgeCloudZoneId(BaseModel):
    """A unique identifier for the Edge Cloud Zone"""

    value: UUID = Field(..., examples=["123e4567-e89b-12d3-a456-426614174000"])


class EdgeCloudRegion(BaseModel):
    """
    The EdgeCloudProvider's name for the region where the Edge Cloud Zone is located.
    """

    value: str = Field(
        ...,
        pattern=DNS_LABEL_PATTERN,
        examples=["us-east-1", "europe-west1"],
    )


class EdgeCloudProvider(BaseModel):
    """The provider of the Edge Cloud"""

    value: str = Field(
        ...,
        pattern=DNS_LABEL_PATTERN,
        examples=["ProviderA"],
    )


class EdgeCloudZoneName(BaseModel):
    """The name of the Edge Cloud Zone"""

    value: str = Field(
        ...,
        pattern=DNS_LABEL_PATTERN,
        examples=["ZoneA"],
    )


class ApplicationEndpointListId(BaseModel):
    """
    A system-defined string identifier representing one or more registered
    Application Endpoints. This ID is generated by the system upon successful
    registration of an application and is used to reference the registered
    endpoints in subsequent operations.
    """

    value: UUID = Field(
        ...,
        examples=["98765432-e89b-12d3-a456-426614174999"],
        description="System-generated UUID for the application endpoint list",
    )

    model_config = ConfigDict(extra="forbid")


class ApplicationProfileId(BaseModel):
    """
    A unique identifier for the application profile. This represents
    the application's network and compute characteristics.
    """

    value: UUID = Field(..., examples=["123e4567-e89b-12d3-a456-426614174000"])


class EdgeCloudZone(BaseModel):
    """
    An Edge Cloud Zone, uniquely identified by a combination of the value
    of the Edge Cloud Zone Id object and the value of the Edge Cloud Provider
    object. This value is used to identify an Edge Cloud zone between Edge
    Clouds from different Edge Cloud Providers.
    """

    edge_cloud_zone_id: EdgeCloudZoneId = Field(..., alias="edgeCloudZoneId")
    edge_cloud_zone_name: EdgeCloudZoneName = Field(..., alias="edgeCloudZoneName")
    edge_cloud_provider: EdgeCloudProvider = Field(..., alias="edgeCloudProvider")
    edge_cloud_zone_status: EdgeCloudZoneStatus = Field(
        EdgeCloudZoneStatus.UNKNOWN, alias="edgeCloudZoneStatus"
    )
    edge_cloud_region: EdgeCloudRegion | None = Field(None, alias="edgeCloudRegion")

    model_config = ConfigDict(populate_by_name=True, use_enum_values=True)
